# Generated by Django 4.1.5 on 2023-02-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=16)),
                ('color', models.CharField(max_length=16)),
                ('slug', models.CharField(max_length=16)),
            ],
        ),
    ]
