# Generated by Django 4.1.5 on 2023-02-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
