# Generated by Django 4.1.5 on 2023-02-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0002_alter_tag_color_alter_tag_name_alter_tag_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tags", models.ManyToManyField(to="tags.tag")),
            ],
        ),
    ]
