# Generated by Django 4.1.5 on 2023-02-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="name",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
