# Generated by Django 4.1.5 on 2023-02-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
