# Generated by Django 4.1.5 on 2023-03-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_alter_ingredient_options_and_more'),
        ('recipes', '0004_alter_recipeingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                through='recipes.RecipeIngredient',
                to='ingredients.ingredient',
                verbose_name='ингредиенты',
            ),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='ingredients.ingredient',
                verbose_name='ingredient',
            ),
        ),
    ]
