# Generated by Django 4.1.5 on 2023-02-03 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipetag_alter_recipe_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipetag",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipetag",
            name="tag",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="RecipeTag",
        ),
    ]
