# Generated by Django 4.1.5 on 2023-03-02 06:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_alter_tag_color_alter_tag_name_alter_tag_slug'),
        ('ingredients', '0005_alter_ingredient_options_and_more'),
        ('recipes', '0007_alter_recipe_options_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={
                'ordering': ['id'],
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='время приготовления',
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                default=None,
                null=True,
                upload_to='recipes/images/',
                verbose_name='изображение',
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                through='recipes.RecipeIngredient',
                to='ingredients.ingredient',
                verbose_name='ингредиенты',
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                blank=True, to='tags.tag', verbose_name='теги'
            ),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(
                blank=True, null=True, verbose_name='текст'
            ),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='ingredients.ingredient',
                verbose_name='ингредиент',
            ),
        ),
    ]
