# Generated by Django 4.1.5 on 2023-02-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_alter_ingredient_measurement_unit_and_more"),
        ("recipes", "0008_ingredienttag_delete_recipetag_alter_recipe_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="IngredientTag",
            new_name="RecipeIngredient",
        ),
    ]
