# Generated by Django 4.1.5 on 2023-02-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_alter_ingredient_measurement_unit_and_more"),
        ("recipes", "0009_rename_ingredienttag_recipeingredient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredients",
                through="recipes.RecipeIngredient",
                to="ingredients.ingredient",
            ),
        ),
    ]
