# Generated by Django 4.1.5 on 2023-02-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_alter_ingredient_measurement_unit_and_more"),
        ("recipes", "0013_alter_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="ingredients_set",
                through="recipes.RecipeIngredient",
                to="ingredients.ingredient",
            ),
        ),
    ]
