# Generated by Django 4.1.5 on 2023-02-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_alter_ingredient_measurement_unit_and_more"),
        ("recipes", "0014_alter_recipe_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipeIngredient", to="ingredients.ingredient"
            ),
        ),
    ]
