# Generated by Django 4.1.5 on 2023-02-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0017_alter_recipe_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=None, null=True, upload_to="recipes/images/"
            ),
        ),
    ]
