# Generated by Django 4.1.5 on 2023-02-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0018_recipe_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="quantity",
            new_name="amount",
        ),
    ]
