# Generated by Django 4.1.5 on 2023-02-10 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0019_rename_quantity_recipeingredient_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="recipe",
            name="favorites",
            field=models.ManyToManyField(
                related_name="favs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
