# Generated by Django 4.1.5 on 2023-02-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_alter_recipe_options_recipe_favorites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="favorites",
        ),
    ]
