# Generated by Django 4.1.5 on 2023-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_remove_recipe_favorites"),
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(to="recipes.recipe"),
        ),
    ]
