# Generated by Django 4.1.5 on 2023-02-11 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscriptions",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
