# Generated by Django 4.1.5 on 2023-02-11 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_remove_recipe_favorites"),
        ("users", "0004_user_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(blank=True, to="recipes.recipe"),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscriptions",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
