# Generated by Django 4.1.5 on 2023-02-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_remove_recipe_favorites"),
        ("users", "0005_alter_user_favorites_alter_user_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shopping_cart",
            field=models.ManyToManyField(
                blank=True, related_name="purchases", to="recipes.recipe"
            ),
        ),
    ]
